services:
  data-gen:
    image: ewanf2/flask-app
    #build: . #testing on local pc
    container_name: data-gen
    ports:
      - "5050:80"
    volumes:
      - schemas:/app/schemas
volumes:
  schemas:
